#ifndef _NETDEFS_H
#define _NETDEFS_H

#define NetInterface CNet::GetInterface()
#define RconInterface CRcon::GetInterface()

#define NETGAME_VERSION 0x10030
#define RCON_VERSION 3010

#define REJECT_REASON_BAD_VERSION   1
#define REJECT_REASON_BAD_NICKNAME  2

#define INVALID_PLAYER_ID 255
#define INVALID_TEAM_ID 255

enum __Part_Reasons
{
	PARTREASON_LOST,
	PARTREASON_CLOSED,
};

enum __Death_Scoring
{
	VALID_KILL = 1,
	TEAM_KILL,
	SELF_KILL,
};

enum __Packet_List
{
	ID_MISC_PACKET = 54, // Defined as 54 because this is where the raknet packets end
	ID_GAME_PACKET,
	ID_PLAYER_PACKET,
	ID_VEHICLE_PACKET,
};

enum __Misc_Packets
{
	ID_MISC_JOINREQUEST,
	ID_MISC_JOINACCEPTED,
	ID_MISC_JOINDECLINED,
	ID_MISC_RCONJOIN,
	ID_MISC_RCONPART,
	ID_MISC_RCONLIST,
	ID_MISC_PLAYERLIST,
	ID_MISC_VEHICLELIST,
	ID_MISC_RCONCHAT,
};

enum __Player_Packets
{
	ID_PLAYER_CHAT,
	ID_PLAYER_JOIN,
	ID_PLAYER_PART,
	ID_PLAYER_ACTION,
	ID_PLAYER_MSG,
	ID_PLAYER_TEAMCHAT,
	ID_PLAYER_SPAWN,
	ID_PLAYER_VEHICLEENTER,
	ID_PLAYER_VEHICLEEXIT,
	ID_PLAYER_KILL,
	ID_PLAYER_TEAMKILL,
	ID_PLAYER_DEATH,
	ID_PLAYER_COMMAND,
	ID_PLAYER_DOANIM,
	ID_PLAYER_PICKEDUPPICKUP,
	ID_PLAYER_SYNCDATA,
};

#endif
