#ifndef _NETDEFS_H
#define _NETDEFS_H

#define RCON_VERSION 3010

#define REJECT_REASON_BAD_VERSION   1
#define REJECT_REASON_BAD_NICKNAME  2

#define INVALID_PLAYER_ID 255
#define INVALID_TEAM_ID 255

enum __Part_Reasons
{
	PARTREASON_LOST,
	PARTREASON_CLOSED,
	PARTREASON_KICKED,
	PARTREASON_BANNED,
};

enum __Death_Scoring
{
	VALID_KILL = 1,
	TEAM_KILL,
	SELF_KILL,
};

enum __Packet_List
{
	ID_MISC_PACKET = 54, // Defined as 54 because this is where the raknet packets end
	ID_GAME_PACKET,
	ID_PLAYER_PACKET,
	ID_VEHICLE_PACKET,
	ID_PICKUP_PACKET,
};

enum __Misc_Packets
{
	ID_MISC_JOINREQUEST,
	ID_MISC_JOINACCEPTED,
	ID_MISC_JOINDECLINED,
	ID_MISC_RCONJOIN,
	ID_MISC_RCONPART,
	ID_MISC_RCONLIST,
	ID_MISC_PLAYERLIST,
	ID_MISC_VEHICLELIST,
	ID_MISC_PICKUPLIST,
	ID_MISC_AMMULIST,
	ID_MISC_RCONCHAT,
	ID_MISC_RCONMSG,
	ID_MISC_RCONANN,
	ID_MISC_RCONANNALL,
	ID_MISC_SETPASSWORD,
	ID_MISC_SERVERDATA,
	ID_MISC_SETMAXPLAYERS,
	ID_MISC_SETSCOREBOARD,
	ID_MISC_SETDRIVEBY,
	ID_MISC_KICK,
	ID_MISC_BANID,
	ID_MISC_BANIP,
	ID_MISC_UNBAN,
	ID_MISC_CHATEXCEPT,
	ID_MISC_CHATPLAYER,
	ID_MISC_CHATTOPLAYER,
	ID_MISC_SETSERVNAME,
	ID_MISC_SETGAMEMODE,
};

enum __Player_Packets
{
	ID_PLAYER_CHAT,
	ID_PLAYER_JOIN,
	ID_PLAYER_PART,
	ID_PLAYER_ACTION,
	ID_PLAYER_MSG,
	ID_PLAYER_TEAMCHAT,
	ID_PLAYER_SPAWN,
	ID_PLAYER_VEHICLEENTER,
	ID_PLAYER_VEHICLEEXIT,
	ID_PLAYER_KILL,
	ID_PLAYER_TEAMKILL,
	ID_PLAYER_DEATH,
	ID_PLAYER_COMMAND,
	ID_PLAYER_DOANIM,
	ID_PLAYER_SYNCDATA,
	ID_PLAYER_SETPOSITION,
	ID_PLAYER_SETHEALTH,
	ID_PLAYER_SETARMOUR,
	ID_PLAYER_SETFROZEN,
	ID_PLAYER_SETWEAPON,
	ID_PLAYER_SETCASH,
	ID_PLAYER_REMOVEMARKER,
	ID_PLAYER_PUTINVEHICLE,
	ID_PLAYER_SETMARKER,
	ID_PLAYER_SETSCORE,
	ID_PLAYER_INCSCORE,
	ID_PLAYER_DECSCORE,
	ID_PLAYER_CREATEPICKUP,
	ID_PLAYER_RESPAWNPICKUP,
	ID_PLAYER_DELETEPICKUP,
	ID_PLAYER_SETMUTE,
	ID_PLAYER_SETIGNORE,
	ID_PLAYER_REQUESTWEAPON,
	ID_PLAYER_REQUESTAMMU,
	ID_PLAYER_REQUESTCLASS,
	ID_PLAYER_STARTSPEC,
	ID_PLAYER_STOPSPEC,
	ID_PLAYER_SETLMARKER,
	ID_PLAYER_REMLMARKER,
};

enum __Vehicle_Packets
{
	ID_VEHICLE_SETPOSITION,
	ID_VEHICLE_SETDOORSTATUS,
	ID_VEHICLE_KILLENGINE,
	ID_VEHICLE_SETHEALTH,
	ID_VEHICLE_SYNCDATA,
};

enum __Game_Packets
{
	ID_GAME_SETWEATHER,
	ID_GAME_SETTIME,
	ID_GAME_SETMARKER,
	ID_GAME_AMMUWEAPON,
	ID_GAME_UPDATETIMERATE,
	ID_GAME_SETTIMERATE,
	ID_GAME_SETWEATHERRATE,
	ID_GAME_SETMARKER4PLAYER,
	ID_GAME_SETMAMMUWEAPON,
};

enum __Pickup_Packets
{
	ID_PICKUP_CREATEPICKUP,
	ID_PICKUP_RESPAWNPICKUP,
	ID_PICKUP_DELETEPICKUP,
	ID_PICKUP_PICKUPONCE,
	ID_PICKUP_SETPICKUPRESPAWNTIME,
	ID_PICKUP_SETRESPAWNTIME,
	ID_PICKUP_RESPAWNPICKUPFORPLAYER,
	ID_PICKUP_PICKEDUP,
};

#endif